name: Reaper

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
        message:
          description: 'why'
          required: false
jobs:
  end_trainer:
    # This job will kill the Equinix host called "packer-builder-host"
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    steps:
      - name: Kill
        run: |
              idd=$(curl -H "X-Auth-Token: ${{ secrets.GENCLOUD_REAPER }}"   https://api.genesiscloud.com/compute/v1/instances | jq -r '.instances[0].id')
              curl -d '{"action": "start"}' -X POST -H "X-Auth-Token: ${{ secrets.GENCLOUD_REAPER }}" -H "Content-Type: application/json"  "https://api.genesiscloud.com/compute/v1/instances/$idd/actions" | jq
